
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.navi.quizcraftweb.backend.parser_lexer.sqlkv;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 10;
  public static final int REL_OP = 15;
  public static final int USUARIO = 6;
  public static final int POR = 5;
  public static final int FILTRAR = 4;
  public static final int DIGIT = 13;
  public static final int STRING = 14;
  public static final int EOF = 0;
  public static final int REPORTE = 3;
  public static final int ID = 12;
  public static final int COMMA = 9;
  public static final int PUNTEO = 8;
  public static final int SELECCIONAR = 2;
  public static final int error = 1;
  public static final int TIEMPO_TOTAL = 7;
  public static final int OR = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECCIONAR",
  "REPORTE",
  "FILTRAR",
  "POR",
  "USUARIO",
  "TIEMPO_TOTAL",
  "PUNTEO",
  "COMMA",
  "AND",
  "OR",
  "ID",
  "DIGIT",
  "STRING",
  "REL_OP"
  };
}

